In [323]:
import numpy as np
import pandas as pd

In [324]:
df = pd.read_csv('./test.csv')
df.head()

    x          y
0  77  79.775152
1  21  23.177279
2  22  25.609262
3  20  17.857388
4  36  41.849864

In [325]:
X = df["x"].values.reshape(-1,1)
y = df["y"].values

In [326]:
import normal_equation_lr
import imp

In [327]:
imp.reload(normal_equation_lr)

In [328]:
# 절편값을 넣어주는 조건으로
lr = normal_equation_lr.LinearRegression(fit_intercept=True)

In [329]:
lr.fit(X,y)

In [330]:
lr.coef

array([1.01433536])

In [331]:
lr.intercept

-0.46181077366111367

In [332]:
lr.predict(X)

array([ 77.64201157,  20.83923168,  21.85356704,  19.82489633,
        36.05426201,  14.75321955,  62.42698124,  95.90004796,
        19.82489633,   4.609866  ,   3.59553065,  18.81056097,
        96.91438332,  62.42698124,  36.05426201,  14.75321955,
        65.46998731,  13.7388842 ,  87.78536512,  69.52732873,
        89.81403583,  51.26929234,  89.81403583,  26.92524381,
        97.92871867,  58.36963982,  79.67068228,  20.83923168,
        93.87137725,  26.92524381,  99.95738938,  30.98258524,
        33.01125595,  80.68501764,  27.93957917,  47.21195092,
        53.29796305,  69.52732873,  27.93957917,  33.01125595,
        91.84270654,  71.55599944,  50.25495698,  76.62767622,
         3.59553065,  37.06859737,  70.54166408,  68.51299337,
        40.11160343,  35.03992666,  94.88571261,  88.79970048,
        52.28362769,  30.98258524,  59.38397518,  -0.46181077,
        39.09726808,  64.45565195,  69.52732873,  57.35530447,
        12.72454884,  72.57033479,  76.62767622,  61.41264589,
        82.71368835,  17.79622562,  41.12593879,  50.25495698,
        55.32663376,  12.72454884,  46.19761556,  12.72454884,
        79.67068228,  53.29796305,  14.75321955,  27.93957917,
        81.69935299,  69.52732873,  52.28362769,  84.74235906,
        68.51299337,  26.92524381,  56.34096911,  48.22628627,
        40.11160343,  39.09726808,  82.71368835, 100.97172474,
        59.38397518,  43.1546095 ,  67.49865802,  38.08293272,
        63.4413166 ,  91.84270654,  60.39831053,  13.7388842 ,
        20.83923168,  87.78536512,  73.58467015,  31.99692059,
         1.56685994,  82.71368835,  18.81056097,  74.59900551,
        42.14027414,  11.71021349,   0.55252458,  90.82837119,
        89.81403583,  -0.46181077,  41.12593879,  15.76755491,
        94.88571261,  97.92871867,  66.48432266,  23.88223775,
        16.78189026,  90.82837119,  12.72454884,  -0.46181077,
        64.45565195,  96.91438332,  98.94305403,  11.71021349,
        41.12593879,  47.21195092,  78.65634693,  19.82489633,
        89.81403583,  28.95391452,  64.45565195,  75.61334086,
        11.71021349,  24.8965731 ,  27.93957917,  29.96824988,
        65.46998731,  59.38397518,  64.45565195,  53.29796305,
        71.55599944,  97.92871867,  73.58467015,   8.66720742,
        11.71021349,  63.4413166 ,  99.95738938,  60.39831053,
        35.03992666,   1.56685994,  60.39831053,  31.99692059,
        94.88571261,  84.74235906,  63.4413166 ,  21.85356704,
        81.69935299,  93.87137725,  33.01125595,   6.63853671,
        42.14027414,  46.19761556,  54.3122984 ,  15.76755491,
        49.24062163,  43.1546095 ,  95.90004796,  66.48432266,
        20.83923168,  35.03992666,  80.68501764,  37.06859737,
        54.3122984 ,  56.34096911,   0.55252458,  31.99692059,
        58.36963982,  31.99692059,  46.19761556,  72.57033479,
        16.78189026,  97.92871867,  93.87137725,  91.84270654,
        37.06859737,   3.59553065,  54.3122984 ,  51.26929234,
        26.92524381,  46.19761556,  92.8570419 ,  73.58467015,
        77.64201157,  91.84270654,  61.41264589,  99.95738938,
         3.59553065,  72.57033479,  18.81056097,  57.35530447,
        78.65634693,  25.91090846,  74.59900551,  90.82837119,
        66.48432266,  12.72454884,  40.11160343,  77.64201157,
        67.49865802,  75.61334086,  22.86790239,  45.18328021,
        59.38397518,  44.16894485,  22.86790239,  55.32663376,
        55.32663376,  95.90004796,  11.71021349,   3.59553065,
         6.63853671, 100.97172474,  48.22628627,  42.14027414,
        96.91438332,  39.09726808, 100.97172474,  87.78536512,
        13.7388842 ,  13.7388842 ,  37.06859737,   4.609866  ,
        88.79970048,  91.84270654,  65.46998731,  74.59900551,
        56.34096911,  15.76755491,   4.609866  ,  27.93957917,
        92.8570419 ,  46.19761556,  54.3122984 ,  39.09726808,
        44.16894485,  30.98258524,  68.51299337,  86.77102977,
        90.82837119,  38.08293272,  20.83923168,  95.90004796,
        56.34096911,  60.39831053,  65.46998731,  78.65634693,
        89.81403583,   5.62420136,  67.49865802,  36.05426201,
        15.76755491, 100.97172474,  45.18328021,  73.58467015,
        57.35530447,  19.82489633,  76.62767622,  34.0255913 ,
        55.32663376,  72.57033479,  55.32663376,   7.65287207,
        56.34096911,  72.57033479,  58.36963982,   5.62420136,
        96.91438332,  22.86790239,  58.36963982,  22.86790239,
        18.81056097,  24.8965731 ,  64.45565195,  20.83923168,
        59.38397518,  18.81056097,  15.76755491,  42.14027414,
        43.1546095 ,  61.41264589,  92.8570419 ,  10.69587813,
        41.12593879,   0.55252458,   7.65287207,  71.55599944,
        46.19761556,  55.32663376,  62.42698124,  47.21195092])